version: "3"
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=skeleton
      - POSTGRES_USER=skeleton_user
      - POSTGRES_PASSWORD=skeleton_pass
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./skeleton/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  db-data:
